#!/usr/bin/env python3
"""Securely configure the tutor.html API connection.

Prompts for the API key with hidden input (nothing echoed to screen,
nothing stored in shell history). Writes tools/tutor-config.js which
tutor.html auto-loads. That file is gitignored — it never leaves your
machine.

Usage:  python3 tools/set-tutor-key.py
"""
import getpass
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "tutor-config.js")
GITIGNORE = os.path.join(os.path.dirname(HERE), ".gitignore")

DEFAULT_URL = "https://api.z.ai/api/coding/paas/v4"
DEFAULT_MODEL = "glm-4.6"


def ask(prompt: str, default: str) -> str:
    val = input(f"{prompt} [{default}]: ").strip()
    return val or default


def main() -> None:
    print("Tutor API setup — values stored locally in tools/tutor-config.js (gitignored)\n")

    url = ask("API base URL", DEFAULT_URL)
    key = getpass.getpass("API key (hidden input): ").strip()
    model = ask("Model", DEFAULT_MODEL)

    if not key:
        print("\nNo key entered — nothing written.")
        sys.exit(1)

    cfg = {"url": url.rstrip("/"), "key": key, "model": model}
    js = (
        "// AUTO-GENERATED by tools/set-tutor-key.py — gitignored, do not commit\n"
        f"window.TUTOR_CFG = {json.dumps(cfg, indent=2)};\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    os.chmod(OUT, 0o600)  # owner read/write only

    # make sure it's never committed
    entry = "tools/tutor-config.js"
    if os.path.exists(GITIGNORE):
        with open(GITIGNORE, encoding="utf-8") as f:
            lines = [ln.strip() for ln in f]
        if entry not in lines:
            with open(GITIGNORE, "a", encoding="utf-8") as f:
                f.write(f"\n{entry}\n")
    else:
        with open(GITIGNORE, "w", encoding="utf-8") as f:
            f.write(f"{entry}\n")

    print(f"\nWrote {OUT} (chmod 600, gitignored)")
    print("Open tools/tutor.html — the tutor dot should turn green.")


if __name__ == "__main__":
    main()
